authorization:
  jwt:
    secret: 'Усердно тренируйтесь, не будьте занудой, наслаждайтесь жизнью и не воспринимайте все всерьез. Zyzz'
    expiration-seconds: 259_200 # 3 дня
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  application:
    name: authorization
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/auth
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml

server:
  port: ${SERVER_HTTP_PORT:8080}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs